2023-08-18 11:28:30,509:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-18 11:28:30,509:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-18 11:28:30,509:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-18 11:28:30,509:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-18 11:28:31,143:WARNING:
'prophet' is a soft dependency and not included in the pycaret installation. Please run: `pip install prophet` to install.
2023-08-18 11:28:31,293:INFO:PyCaret ClassificationExperiment
2023-08-18 11:28:31,293:INFO:Logging name: clf-default-name
2023-08-18 11:28:31,293:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-18 11:28:31,293:INFO:version 3.0.2
2023-08-18 11:28:31,293:INFO:Initializing setup()
2023-08-18 11:28:31,293:INFO:self.USI: 1db3
2023-08-18 11:28:31,293:INFO:self._variable_keys: {'fold_generator', 'X', 'gpu_param', 'X_test', 'y_train', 'memory', 'idx', 'html_param', 'y', 'fix_imbalance', '_available_plots', '_ml_usecase', 'gpu_n_jobs_param', 'exp_name_log', 'n_jobs_param', 'fold_groups_param', 'target_param', 'is_multiclass', 'logging_param', 'seed', 'data', 'fold_shuffle_param', 'USI', 'y_test', 'log_plots_param', 'pipeline', 'exp_id', 'X_train'}
2023-08-18 11:28:31,293:INFO:Checking environment
2023-08-18 11:28:31,293:INFO:python_version: 3.9.15
2023-08-18 11:28:31,293:INFO:python_build: ('main', 'Nov 24 2022 14:39:17')
2023-08-18 11:28:31,293:INFO:machine: AMD64
2023-08-18 11:28:31,293:INFO:platform: Windows-10-10.0.22610-SP0
2023-08-18 11:28:31,297:INFO:Memory: svmem(total=34257608704, available=23702249472, percent=30.8, used=10555359232, free=23702249472)
2023-08-18 11:28:31,297:INFO:Physical Core: 6
2023-08-18 11:28:31,297:INFO:Logical Core: 12
2023-08-18 11:28:31,297:INFO:Checking libraries
2023-08-18 11:28:31,297:INFO:System:
2023-08-18 11:28:31,297:INFO:    python: 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
2023-08-18 11:28:31,297:INFO:executable: c:\Users\Admin\miniconda3\python.exe
2023-08-18 11:28:31,297:INFO:   machine: Windows-10-10.0.22610-SP0
2023-08-18 11:28:31,297:INFO:PyCaret required dependencies:
2023-08-18 11:28:31,297:INFO:                 pip: 22.3.1
2023-08-18 11:28:31,297:INFO:          setuptools: 65.5.0
2023-08-18 11:28:31,297:INFO:             pycaret: 3.0.2
2023-08-18 11:28:31,297:INFO:             IPython: 8.7.0
2023-08-18 11:28:31,297:INFO:          ipywidgets: 8.0.6
2023-08-18 11:28:31,297:INFO:                tqdm: 4.64.1
2023-08-18 11:28:31,297:INFO:               numpy: 1.23.4
2023-08-18 11:28:31,297:INFO:              pandas: 1.5.2
2023-08-18 11:28:31,297:INFO:              jinja2: 3.1.2
2023-08-18 11:28:31,298:INFO:               scipy: 1.9.3
2023-08-18 11:28:31,298:INFO:              joblib: 1.2.0
2023-08-18 11:28:31,298:INFO:             sklearn: 1.1.3
2023-08-18 11:28:31,298:INFO:                pyod: 1.0.9
2023-08-18 11:28:31,298:INFO:            imblearn: 0.10.1
2023-08-18 11:28:31,298:INFO:   category_encoders: 2.6.1
2023-08-18 11:28:31,298:INFO:            lightgbm: 3.3.5
2023-08-18 11:28:31,298:INFO:               numba: 0.57.0
2023-08-18 11:28:31,298:INFO:            requests: 2.28.1
2023-08-18 11:28:31,298:INFO:          matplotlib: 3.6.2
2023-08-18 11:28:31,298:INFO:          scikitplot: 0.3.7
2023-08-18 11:28:31,298:INFO:         yellowbrick: 1.5
2023-08-18 11:28:31,298:INFO:              plotly: 5.11.0
2023-08-18 11:28:31,298:INFO:             kaleido: 0.2.1
2023-08-18 11:28:31,298:INFO:         statsmodels: 0.14.0
2023-08-18 11:28:31,298:INFO:              sktime: 0.17.0
2023-08-18 11:28:31,298:INFO:               tbats: 1.1.3
2023-08-18 11:28:31,298:INFO:            pmdarima: 2.0.3
2023-08-18 11:28:31,298:INFO:              psutil: 5.9.0
2023-08-18 11:28:31,298:INFO:PyCaret optional dependencies:
2023-08-18 11:28:32,262:INFO:                shap: Not installed
2023-08-18 11:28:32,262:INFO:           interpret: Not installed
2023-08-18 11:28:32,262:INFO:                umap: Not installed
2023-08-18 11:28:32,262:INFO:    pandas_profiling: Not installed
2023-08-18 11:28:32,262:INFO:  explainerdashboard: Not installed
2023-08-18 11:28:32,262:INFO:             autoviz: Not installed
2023-08-18 11:28:32,262:INFO:           fairlearn: Not installed
2023-08-18 11:28:32,262:INFO:             xgboost: Not installed
2023-08-18 11:28:32,262:INFO:            catboost: Not installed
2023-08-18 11:28:32,262:INFO:              kmodes: Not installed
2023-08-18 11:28:32,262:INFO:             mlxtend: 0.22.0
2023-08-18 11:28:32,262:INFO:       statsforecast: Not installed
2023-08-18 11:28:32,262:INFO:        tune_sklearn: Not installed
2023-08-18 11:28:32,262:INFO:                 ray: Not installed
2023-08-18 11:28:32,262:INFO:            hyperopt: Not installed
2023-08-18 11:28:32,262:INFO:              optuna: Not installed
2023-08-18 11:28:32,262:INFO:               skopt: Not installed
2023-08-18 11:28:32,262:INFO:              mlflow: Not installed
2023-08-18 11:28:32,262:INFO:              gradio: 3.39.0
2023-08-18 11:28:32,262:INFO:             fastapi: 0.86.0
2023-08-18 11:28:32,262:INFO:             uvicorn: 0.19.0
2023-08-18 11:28:32,262:INFO:              m2cgen: Not installed
2023-08-18 11:28:32,262:INFO:           evidently: Not installed
2023-08-18 11:28:32,262:INFO:               fugue: Not installed
2023-08-18 11:28:32,262:INFO:           streamlit: 1.14.0
2023-08-18 11:28:32,262:INFO:             prophet: Not installed
2023-08-18 11:28:32,262:INFO:None
2023-08-18 11:28:32,263:INFO:Set up data.
2023-08-18 11:28:32,268:INFO:Set up train/test split.
2023-08-18 11:28:32,273:INFO:Set up index.
2023-08-18 11:28:32,273:INFO:Set up folding strategy.
2023-08-18 11:28:32,273:INFO:Assigning column types.
2023-08-18 11:28:32,275:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-18 11:28:32,307:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-18 11:28:32,308:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-18 11:28:32,333:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,348:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,381:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-18 11:28:32,381:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-18 11:28:32,401:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,401:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,401:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-08-18 11:28:32,434:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-18 11:28:32,453:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,454:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,486:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-18 11:28:32,505:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,506:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,506:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-08-18 11:28:32,558:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,558:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,610:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,611:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,613:INFO:Preparing preprocessing pipeline...
2023-08-18 11:28:32,614:INFO:Set up label encoding.
2023-08-18 11:28:32,614:INFO:Set up simple imputation.
2023-08-18 11:28:32,616:INFO:Set up encoding of ordinal features.
2023-08-18 11:28:32,616:INFO:Set up encoding of categorical features.
2023-08-18 11:28:32,645:INFO:Finished creating preprocessing pipeline.
2023-08-18 11:28:32,656:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\Admin\AppData\Local\Temp\joblib),
         steps=[('label_encoding',
                 TransformerWrapperWithInverse(exclude=None, include=None,
                                               transformer=LabelEncoder())),
                ('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'tb', 'db', 'alkphos',
                                             'sgpt', 'sgot', 'tp', 'alb',
                                             'ag_ratio'],
                                    transformer=SimpleImputer(add_indicat...
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('ordinal_encoding',
                 TransformerWrapper(exclude=None, include=['gender'],
                                    transformer=OrdinalEncoder(cols=['gender'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               mapping=[{'col': 'gender',
                                                                         'data_type': dtype('O'),
                                                                         'mapping': Female    0
Male      1
NaN      -1
dtype: int64}],
                                                               return_df=True,
                                                               verbose=0)))],
         verbose=False)
2023-08-18 11:28:32,656:INFO:Creating final display dataframe.
2023-08-18 11:28:32,748:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target             class
2                   Target type            Binary
3                Target mapping        1: 0, 2: 1
4           Original data shape         (583, 11)
5        Transformed data shape         (583, 11)
6   Transformed train set shape         (408, 11)
7    Transformed test set shape         (175, 11)
8              Ordinal features                 1
9              Numeric features                 9
10         Categorical features                 1
11     Rows with missing values              0.7%
12                   Preprocess              True
13              Imputation type            simple
14           Numeric imputation              mean
15       Categorical imputation              mode
16     Maximum one-hot encoding                25
17              Encoding method              None
18               Fold Generator   StratifiedKFold
19                  Fold Number                10
20                     CPU Jobs                -1
21                      Use GPU             False
22               Log Experiment             False
23              Experiment Name  clf-default-name
24                          USI              1db3
2023-08-18 11:28:32,804:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,804:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,857:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,857:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-18 11:28:32,858:INFO:setup() successfully completed in 1.57s...............
2023-08-18 11:29:50,485:INFO:Initializing compare_models()
2023-08-18 11:29:50,486:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-08-18 11:29:50,486:INFO:Checking exceptions
2023-08-18 11:29:50,489:INFO:Preparing display monitor
2023-08-18 11:29:50,505:INFO:Initializing Logistic Regression
2023-08-18 11:29:50,505:INFO:Total runtime is 0.0 minutes
2023-08-18 11:29:50,507:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:50,508:INFO:Initializing create_model()
2023-08-18 11:29:50,508:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:50,508:INFO:Checking exceptions
2023-08-18 11:29:50,508:INFO:Importing libraries
2023-08-18 11:29:50,508:INFO:Copying training dataset
2023-08-18 11:29:50,512:INFO:Defining folds
2023-08-18 11:29:50,512:INFO:Declaring metric variables
2023-08-18 11:29:50,515:INFO:Importing untrained model
2023-08-18 11:29:50,518:INFO:Logistic Regression Imported successfully
2023-08-18 11:29:50,525:INFO:Starting cross validation
2023-08-18 11:29:50,526:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:53,928:INFO:Calculating mean and std
2023-08-18 11:29:53,930:INFO:Creating metrics dataframe
2023-08-18 11:29:53,935:INFO:Uploading results into container
2023-08-18 11:29:53,936:INFO:Uploading model into container now
2023-08-18 11:29:53,936:INFO:_master_model_container: 1
2023-08-18 11:29:53,936:INFO:_display_container: 2
2023-08-18 11:29:53,936:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-18 11:29:53,937:INFO:create_model() successfully completed......................................
2023-08-18 11:29:54,040:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:54,040:INFO:Creating metrics dataframe
2023-08-18 11:29:54,046:INFO:Initializing K Neighbors Classifier
2023-08-18 11:29:54,046:INFO:Total runtime is 0.059021766980489096 minutes
2023-08-18 11:29:54,049:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:54,049:INFO:Initializing create_model()
2023-08-18 11:29:54,049:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:54,049:INFO:Checking exceptions
2023-08-18 11:29:54,049:INFO:Importing libraries
2023-08-18 11:29:54,049:INFO:Copying training dataset
2023-08-18 11:29:54,051:INFO:Defining folds
2023-08-18 11:29:54,052:INFO:Declaring metric variables
2023-08-18 11:29:54,054:INFO:Importing untrained model
2023-08-18 11:29:54,056:INFO:K Neighbors Classifier Imported successfully
2023-08-18 11:29:54,060:INFO:Starting cross validation
2023-08-18 11:29:54,061:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:55,607:INFO:Calculating mean and std
2023-08-18 11:29:55,608:INFO:Creating metrics dataframe
2023-08-18 11:29:55,612:INFO:Uploading results into container
2023-08-18 11:29:55,612:INFO:Uploading model into container now
2023-08-18 11:29:55,613:INFO:_master_model_container: 2
2023-08-18 11:29:55,613:INFO:_display_container: 2
2023-08-18 11:29:55,613:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-08-18 11:29:55,613:INFO:create_model() successfully completed......................................
2023-08-18 11:29:55,697:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:55,697:INFO:Creating metrics dataframe
2023-08-18 11:29:55,704:INFO:Initializing Naive Bayes
2023-08-18 11:29:55,704:INFO:Total runtime is 0.0866484800974528 minutes
2023-08-18 11:29:55,706:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:55,706:INFO:Initializing create_model()
2023-08-18 11:29:55,707:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:55,707:INFO:Checking exceptions
2023-08-18 11:29:55,707:INFO:Importing libraries
2023-08-18 11:29:55,707:INFO:Copying training dataset
2023-08-18 11:29:55,709:INFO:Defining folds
2023-08-18 11:29:55,709:INFO:Declaring metric variables
2023-08-18 11:29:55,712:INFO:Importing untrained model
2023-08-18 11:29:55,714:INFO:Naive Bayes Imported successfully
2023-08-18 11:29:55,720:INFO:Starting cross validation
2023-08-18 11:29:55,721:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:55,869:INFO:Calculating mean and std
2023-08-18 11:29:55,870:INFO:Creating metrics dataframe
2023-08-18 11:29:55,874:INFO:Uploading results into container
2023-08-18 11:29:55,874:INFO:Uploading model into container now
2023-08-18 11:29:55,874:INFO:_master_model_container: 3
2023-08-18 11:29:55,874:INFO:_display_container: 2
2023-08-18 11:29:55,874:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-08-18 11:29:55,874:INFO:create_model() successfully completed......................................
2023-08-18 11:29:55,950:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:55,950:INFO:Creating metrics dataframe
2023-08-18 11:29:55,957:INFO:Initializing Decision Tree Classifier
2023-08-18 11:29:55,957:INFO:Total runtime is 0.0908714214960734 minutes
2023-08-18 11:29:55,959:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:55,960:INFO:Initializing create_model()
2023-08-18 11:29:55,960:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:55,960:INFO:Checking exceptions
2023-08-18 11:29:55,960:INFO:Importing libraries
2023-08-18 11:29:55,960:INFO:Copying training dataset
2023-08-18 11:29:55,962:INFO:Defining folds
2023-08-18 11:29:55,962:INFO:Declaring metric variables
2023-08-18 11:29:55,964:INFO:Importing untrained model
2023-08-18 11:29:55,966:INFO:Decision Tree Classifier Imported successfully
2023-08-18 11:29:55,970:INFO:Starting cross validation
2023-08-18 11:29:55,971:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:56,122:INFO:Calculating mean and std
2023-08-18 11:29:56,123:INFO:Creating metrics dataframe
2023-08-18 11:29:56,126:INFO:Uploading results into container
2023-08-18 11:29:56,126:INFO:Uploading model into container now
2023-08-18 11:29:56,127:INFO:_master_model_container: 4
2023-08-18 11:29:56,127:INFO:_display_container: 2
2023-08-18 11:29:56,127:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-08-18 11:29:56,127:INFO:create_model() successfully completed......................................
2023-08-18 11:29:56,200:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:56,200:INFO:Creating metrics dataframe
2023-08-18 11:29:56,207:INFO:Initializing SVM - Linear Kernel
2023-08-18 11:29:56,207:INFO:Total runtime is 0.0950287898381551 minutes
2023-08-18 11:29:56,209:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:56,209:INFO:Initializing create_model()
2023-08-18 11:29:56,209:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:56,210:INFO:Checking exceptions
2023-08-18 11:29:56,210:INFO:Importing libraries
2023-08-18 11:29:56,210:INFO:Copying training dataset
2023-08-18 11:29:56,212:INFO:Defining folds
2023-08-18 11:29:56,212:INFO:Declaring metric variables
2023-08-18 11:29:56,214:INFO:Importing untrained model
2023-08-18 11:29:56,216:INFO:SVM - Linear Kernel Imported successfully
2023-08-18 11:29:56,220:INFO:Starting cross validation
2023-08-18 11:29:56,220:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:56,320:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,320:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,324:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,325:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,326:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,327:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,328:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,333:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,334:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,335:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,336:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,337:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,339:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 127, in __get__
    if not self.check(obj):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1222, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-18 11:29:56,341:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,343:INFO:Calculating mean and std
2023-08-18 11:29:56,344:INFO:Creating metrics dataframe
2023-08-18 11:29:56,347:INFO:Uploading results into container
2023-08-18 11:29:56,348:INFO:Uploading model into container now
2023-08-18 11:29:56,348:INFO:_master_model_container: 5
2023-08-18 11:29:56,348:INFO:_display_container: 2
2023-08-18 11:29:56,348:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-08-18 11:29:56,348:INFO:create_model() successfully completed......................................
2023-08-18 11:29:56,424:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:56,424:INFO:Creating metrics dataframe
2023-08-18 11:29:56,431:INFO:Initializing Ridge Classifier
2023-08-18 11:29:56,431:INFO:Total runtime is 0.09876880645751952 minutes
2023-08-18 11:29:56,434:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:56,434:INFO:Initializing create_model()
2023-08-18 11:29:56,434:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:56,434:INFO:Checking exceptions
2023-08-18 11:29:56,434:INFO:Importing libraries
2023-08-18 11:29:56,434:INFO:Copying training dataset
2023-08-18 11:29:56,437:INFO:Defining folds
2023-08-18 11:29:56,437:INFO:Declaring metric variables
2023-08-18 11:29:56,439:INFO:Importing untrained model
2023-08-18 11:29:56,442:INFO:Ridge Classifier Imported successfully
2023-08-18 11:29:56,446:INFO:Starting cross validation
2023-08-18 11:29:56,447:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:56,552:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,552:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,554:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,556:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,557:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,561:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,562:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,562:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,563:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,563:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,566:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,567:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 74, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 301, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Admin\miniconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-18 11:29:56,567:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,568:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:56,570:INFO:Calculating mean and std
2023-08-18 11:29:56,571:INFO:Creating metrics dataframe
2023-08-18 11:29:56,574:INFO:Uploading results into container
2023-08-18 11:29:56,575:INFO:Uploading model into container now
2023-08-18 11:29:56,575:INFO:_master_model_container: 6
2023-08-18 11:29:56,575:INFO:_display_container: 2
2023-08-18 11:29:56,575:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize='deprecated', positive=False,
                random_state=123, solver='auto', tol=0.001)
2023-08-18 11:29:56,575:INFO:create_model() successfully completed......................................
2023-08-18 11:29:56,651:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:56,652:INFO:Creating metrics dataframe
2023-08-18 11:29:56,659:INFO:Initializing Random Forest Classifier
2023-08-18 11:29:56,659:INFO:Total runtime is 0.1025618275006612 minutes
2023-08-18 11:29:56,661:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:56,661:INFO:Initializing create_model()
2023-08-18 11:29:56,661:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:56,661:INFO:Checking exceptions
2023-08-18 11:29:56,661:INFO:Importing libraries
2023-08-18 11:29:56,661:INFO:Copying training dataset
2023-08-18 11:29:56,664:INFO:Defining folds
2023-08-18 11:29:56,664:INFO:Declaring metric variables
2023-08-18 11:29:56,666:INFO:Importing untrained model
2023-08-18 11:29:56,668:INFO:Random Forest Classifier Imported successfully
2023-08-18 11:29:56,672:INFO:Starting cross validation
2023-08-18 11:29:56,673:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:57,301:INFO:Calculating mean and std
2023-08-18 11:29:57,302:INFO:Creating metrics dataframe
2023-08-18 11:29:57,311:INFO:Uploading results into container
2023-08-18 11:29:57,311:INFO:Uploading model into container now
2023-08-18 11:29:57,312:INFO:_master_model_container: 7
2023-08-18 11:29:57,312:INFO:_display_container: 2
2023-08-18 11:29:57,312:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-08-18 11:29:57,312:INFO:create_model() successfully completed......................................
2023-08-18 11:29:57,389:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:57,389:INFO:Creating metrics dataframe
2023-08-18 11:29:57,396:INFO:Initializing Quadratic Discriminant Analysis
2023-08-18 11:29:57,396:INFO:Total runtime is 0.11485415299733479 minutes
2023-08-18 11:29:57,398:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:57,399:INFO:Initializing create_model()
2023-08-18 11:29:57,399:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:57,399:INFO:Checking exceptions
2023-08-18 11:29:57,399:INFO:Importing libraries
2023-08-18 11:29:57,399:INFO:Copying training dataset
2023-08-18 11:29:57,401:INFO:Defining folds
2023-08-18 11:29:57,401:INFO:Declaring metric variables
2023-08-18 11:29:57,403:INFO:Importing untrained model
2023-08-18 11:29:57,405:INFO:Quadratic Discriminant Analysis Imported successfully
2023-08-18 11:29:57,410:INFO:Starting cross validation
2023-08-18 11:29:57,411:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:57,574:INFO:Calculating mean and std
2023-08-18 11:29:57,575:INFO:Creating metrics dataframe
2023-08-18 11:29:57,582:INFO:Uploading results into container
2023-08-18 11:29:57,582:INFO:Uploading model into container now
2023-08-18 11:29:57,583:INFO:_master_model_container: 8
2023-08-18 11:29:57,583:INFO:_display_container: 2
2023-08-18 11:29:57,583:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-08-18 11:29:57,583:INFO:create_model() successfully completed......................................
2023-08-18 11:29:57,658:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:57,658:INFO:Creating metrics dataframe
2023-08-18 11:29:57,666:INFO:Initializing Ada Boost Classifier
2023-08-18 11:29:57,666:INFO:Total runtime is 0.1193568468093872 minutes
2023-08-18 11:29:57,669:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:57,669:INFO:Initializing create_model()
2023-08-18 11:29:57,669:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:57,669:INFO:Checking exceptions
2023-08-18 11:29:57,669:INFO:Importing libraries
2023-08-18 11:29:57,669:INFO:Copying training dataset
2023-08-18 11:29:57,671:INFO:Defining folds
2023-08-18 11:29:57,671:INFO:Declaring metric variables
2023-08-18 11:29:57,673:INFO:Importing untrained model
2023-08-18 11:29:57,675:INFO:Ada Boost Classifier Imported successfully
2023-08-18 11:29:57,679:INFO:Starting cross validation
2023-08-18 11:29:57,680:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:57,953:INFO:Calculating mean and std
2023-08-18 11:29:57,954:INFO:Creating metrics dataframe
2023-08-18 11:29:57,961:INFO:Uploading results into container
2023-08-18 11:29:57,962:INFO:Uploading model into container now
2023-08-18 11:29:57,962:INFO:_master_model_container: 9
2023-08-18 11:29:57,962:INFO:_display_container: 2
2023-08-18 11:29:57,962:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=123)
2023-08-18 11:29:57,962:INFO:create_model() successfully completed......................................
2023-08-18 11:29:58,037:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:58,038:INFO:Creating metrics dataframe
2023-08-18 11:29:58,045:INFO:Initializing Gradient Boosting Classifier
2023-08-18 11:29:58,045:INFO:Total runtime is 0.1256742755572001 minutes
2023-08-18 11:29:58,048:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:58,048:INFO:Initializing create_model()
2023-08-18 11:29:58,048:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:58,048:INFO:Checking exceptions
2023-08-18 11:29:58,048:INFO:Importing libraries
2023-08-18 11:29:58,048:INFO:Copying training dataset
2023-08-18 11:29:58,050:INFO:Defining folds
2023-08-18 11:29:58,050:INFO:Declaring metric variables
2023-08-18 11:29:58,052:INFO:Importing untrained model
2023-08-18 11:29:58,055:INFO:Gradient Boosting Classifier Imported successfully
2023-08-18 11:29:58,059:INFO:Starting cross validation
2023-08-18 11:29:58,060:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:58,364:INFO:Calculating mean and std
2023-08-18 11:29:58,364:INFO:Creating metrics dataframe
2023-08-18 11:29:58,371:INFO:Uploading results into container
2023-08-18 11:29:58,372:INFO:Uploading model into container now
2023-08-18 11:29:58,372:INFO:_master_model_container: 10
2023-08-18 11:29:58,372:INFO:_display_container: 2
2023-08-18 11:29:58,373:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-18 11:29:58,373:INFO:create_model() successfully completed......................................
2023-08-18 11:29:58,447:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:58,447:INFO:Creating metrics dataframe
2023-08-18 11:29:58,455:INFO:Initializing Linear Discriminant Analysis
2023-08-18 11:29:58,455:INFO:Total runtime is 0.13249658743540443 minutes
2023-08-18 11:29:58,457:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:58,457:INFO:Initializing create_model()
2023-08-18 11:29:58,457:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:58,457:INFO:Checking exceptions
2023-08-18 11:29:58,457:INFO:Importing libraries
2023-08-18 11:29:58,457:INFO:Copying training dataset
2023-08-18 11:29:58,459:INFO:Defining folds
2023-08-18 11:29:58,459:INFO:Declaring metric variables
2023-08-18 11:29:58,461:INFO:Importing untrained model
2023-08-18 11:29:58,464:INFO:Linear Discriminant Analysis Imported successfully
2023-08-18 11:29:58,468:INFO:Starting cross validation
2023-08-18 11:29:58,468:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:58,615:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:58,616:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:58,626:INFO:Calculating mean and std
2023-08-18 11:29:58,627:INFO:Creating metrics dataframe
2023-08-18 11:29:58,634:INFO:Uploading results into container
2023-08-18 11:29:58,634:INFO:Uploading model into container now
2023-08-18 11:29:58,634:INFO:_master_model_container: 11
2023-08-18 11:29:58,634:INFO:_display_container: 2
2023-08-18 11:29:58,635:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-08-18 11:29:58,635:INFO:create_model() successfully completed......................................
2023-08-18 11:29:58,712:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:58,712:INFO:Creating metrics dataframe
2023-08-18 11:29:58,720:INFO:Initializing Extra Trees Classifier
2023-08-18 11:29:58,720:INFO:Total runtime is 0.13691465457280474 minutes
2023-08-18 11:29:58,722:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:58,722:INFO:Initializing create_model()
2023-08-18 11:29:58,722:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:58,722:INFO:Checking exceptions
2023-08-18 11:29:58,722:INFO:Importing libraries
2023-08-18 11:29:58,722:INFO:Copying training dataset
2023-08-18 11:29:58,725:INFO:Defining folds
2023-08-18 11:29:58,725:INFO:Declaring metric variables
2023-08-18 11:29:58,727:INFO:Importing untrained model
2023-08-18 11:29:58,729:INFO:Extra Trees Classifier Imported successfully
2023-08-18 11:29:58,734:INFO:Starting cross validation
2023-08-18 11:29:58,734:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:59,280:INFO:Calculating mean and std
2023-08-18 11:29:59,280:INFO:Creating metrics dataframe
2023-08-18 11:29:59,289:INFO:Uploading results into container
2023-08-18 11:29:59,290:INFO:Uploading model into container now
2023-08-18 11:29:59,290:INFO:_master_model_container: 12
2023-08-18 11:29:59,290:INFO:_display_container: 2
2023-08-18 11:29:59,291:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-08-18 11:29:59,291:INFO:create_model() successfully completed......................................
2023-08-18 11:29:59,368:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:59,368:INFO:Creating metrics dataframe
2023-08-18 11:29:59,376:INFO:Initializing Light Gradient Boosting Machine
2023-08-18 11:29:59,376:INFO:Total runtime is 0.1478586157162984 minutes
2023-08-18 11:29:59,379:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:59,379:INFO:Initializing create_model()
2023-08-18 11:29:59,379:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:59,379:INFO:Checking exceptions
2023-08-18 11:29:59,379:INFO:Importing libraries
2023-08-18 11:29:59,379:INFO:Copying training dataset
2023-08-18 11:29:59,381:INFO:Defining folds
2023-08-18 11:29:59,382:INFO:Declaring metric variables
2023-08-18 11:29:59,384:INFO:Importing untrained model
2023-08-18 11:29:59,386:INFO:Light Gradient Boosting Machine Imported successfully
2023-08-18 11:29:59,390:INFO:Starting cross validation
2023-08-18 11:29:59,390:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:59,625:INFO:Calculating mean and std
2023-08-18 11:29:59,626:INFO:Creating metrics dataframe
2023-08-18 11:29:59,635:INFO:Uploading results into container
2023-08-18 11:29:59,635:INFO:Uploading model into container now
2023-08-18 11:29:59,636:INFO:_master_model_container: 13
2023-08-18 11:29:59,636:INFO:_display_container: 2
2023-08-18 11:29:59,636:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2023-08-18 11:29:59,636:INFO:create_model() successfully completed......................................
2023-08-18 11:29:59,712:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:59,712:INFO:Creating metrics dataframe
2023-08-18 11:29:59,721:INFO:Initializing Dummy Classifier
2023-08-18 11:29:59,721:INFO:Total runtime is 0.15359659989674884 minutes
2023-08-18 11:29:59,723:INFO:SubProcess create_model() called ==================================
2023-08-18 11:29:59,723:INFO:Initializing create_model()
2023-08-18 11:29:59,723:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001F121101E80>, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:59,723:INFO:Checking exceptions
2023-08-18 11:29:59,723:INFO:Importing libraries
2023-08-18 11:29:59,723:INFO:Copying training dataset
2023-08-18 11:29:59,725:INFO:Defining folds
2023-08-18 11:29:59,725:INFO:Declaring metric variables
2023-08-18 11:29:59,727:INFO:Importing untrained model
2023-08-18 11:29:59,730:INFO:Dummy Classifier Imported successfully
2023-08-18 11:29:59,735:INFO:Starting cross validation
2023-08-18 11:29:59,735:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-18 11:29:59,844:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,858:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,859:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,859:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,863:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,871:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,873:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,875:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,877:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,883:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-18 11:29:59,899:INFO:Calculating mean and std
2023-08-18 11:29:59,899:INFO:Creating metrics dataframe
2023-08-18 11:29:59,908:INFO:Uploading results into container
2023-08-18 11:29:59,908:INFO:Uploading model into container now
2023-08-18 11:29:59,909:INFO:_master_model_container: 14
2023-08-18 11:29:59,909:INFO:_display_container: 2
2023-08-18 11:29:59,909:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-08-18 11:29:59,909:INFO:create_model() successfully completed......................................
2023-08-18 11:29:59,984:INFO:SubProcess create_model() end ==================================
2023-08-18 11:29:59,984:INFO:Creating metrics dataframe
2023-08-18 11:29:59,998:INFO:Initializing create_model()
2023-08-18 11:29:59,998:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-08-18 11:29:59,998:INFO:Checking exceptions
2023-08-18 11:29:59,999:INFO:Importing libraries
2023-08-18 11:29:59,999:INFO:Copying training dataset
2023-08-18 11:30:00,001:INFO:Defining folds
2023-08-18 11:30:00,001:INFO:Declaring metric variables
2023-08-18 11:30:00,001:INFO:Importing untrained model
2023-08-18 11:30:00,001:INFO:Declaring custom model
2023-08-18 11:30:00,002:INFO:Logistic Regression Imported successfully
2023-08-18 11:30:00,002:INFO:Cross validation set to False
2023-08-18 11:30:00,002:INFO:Fitting Model
2023-08-18 11:30:00,073:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-18 11:30:00,073:INFO:create_model() successfully completed......................................
2023-08-18 11:30:00,175:INFO:_master_model_container: 14
2023-08-18 11:30:00,175:INFO:_display_container: 2
2023-08-18 11:30:00,176:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-18 11:30:00,176:INFO:compare_models() successfully completed......................................
2023-08-18 11:31:15,233:INFO:Initializing evaluate_model()
2023-08-18 11:31:15,233:INFO:evaluate_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=None, fit_kwargs=None, plot_kwargs=None, feature_name=None, groups=None, use_train_data=False)
2023-08-18 11:31:15,241:INFO:Initializing plot_model()
2023-08-18 11:31:15,241:INFO:plot_model(plot=pipeline, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:31:15,241:INFO:Checking exceptions
2023-08-18 11:31:15,242:INFO:Preloading libraries
2023-08-18 11:31:15,242:INFO:Copying training dataset
2023-08-18 11:31:15,242:INFO:Plot type: pipeline
2023-08-18 11:31:15,362:INFO:Visual Rendered Successfully
2023-08-18 11:31:15,441:INFO:plot_model() successfully completed......................................
2023-08-18 11:31:24,770:INFO:Initializing plot_model()
2023-08-18 11:31:24,770:INFO:plot_model(plot=feature, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:31:24,771:INFO:Checking exceptions
2023-08-18 11:31:24,772:INFO:Preloading libraries
2023-08-18 11:31:24,772:INFO:Copying training dataset
2023-08-18 11:31:24,772:INFO:Plot type: feature
2023-08-18 11:31:24,903:INFO:Visual Rendered Successfully
2023-08-18 11:31:24,973:INFO:plot_model() successfully completed......................................
2023-08-18 11:32:02,544:INFO:Initializing plot_model()
2023-08-18 11:32:02,544:INFO:plot_model(plot=boundary, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:32:02,544:INFO:Checking exceptions
2023-08-18 11:32:02,546:INFO:Preloading libraries
2023-08-18 11:32:02,546:INFO:Copying training dataset
2023-08-18 11:32:02,546:INFO:Plot type: boundary
2023-08-18 11:32:02,592:INFO:Fitting StandardScaler()
2023-08-18 11:32:02,595:INFO:Fitting PCA()
2023-08-18 11:32:02,638:INFO:Fitting Model
2023-08-18 11:32:03,234:INFO:Visual Rendered Successfully
2023-08-18 11:32:03,340:INFO:plot_model() successfully completed......................................
2023-08-18 11:32:17,295:INFO:Initializing plot_model()
2023-08-18 11:32:17,295:INFO:plot_model(plot=pipeline, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:32:17,295:INFO:Checking exceptions
2023-08-18 11:32:17,297:INFO:Preloading libraries
2023-08-18 11:32:17,297:INFO:Copying training dataset
2023-08-18 11:32:17,297:INFO:Plot type: pipeline
2023-08-18 11:32:17,366:INFO:Visual Rendered Successfully
2023-08-18 11:32:17,440:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:12,255:INFO:Initializing plot_model()
2023-08-18 11:33:12,255:INFO:plot_model(plot=parameter, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:12,255:INFO:Checking exceptions
2023-08-18 11:33:12,257:INFO:Preloading libraries
2023-08-18 11:33:12,257:INFO:Copying training dataset
2023-08-18 11:33:12,257:INFO:Plot type: parameter
2023-08-18 11:33:12,259:INFO:Visual Rendered Successfully
2023-08-18 11:33:12,336:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:18,912:INFO:Initializing plot_model()
2023-08-18 11:33:18,912:INFO:plot_model(plot=auc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:18,912:INFO:Checking exceptions
2023-08-18 11:33:18,913:INFO:Preloading libraries
2023-08-18 11:33:18,913:INFO:Copying training dataset
2023-08-18 11:33:18,913:INFO:Plot type: auc
2023-08-18 11:33:18,998:INFO:Fitting Model
2023-08-18 11:33:18,999:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

2023-08-18 11:33:18,999:INFO:Scoring test/hold-out set
2023-08-18 11:33:19,107:INFO:Visual Rendered Successfully
2023-08-18 11:33:19,176:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:22,895:INFO:Initializing plot_model()
2023-08-18 11:33:22,895:INFO:plot_model(plot=confusion_matrix, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:22,895:INFO:Checking exceptions
2023-08-18 11:33:22,896:INFO:Preloading libraries
2023-08-18 11:33:22,897:INFO:Copying training dataset
2023-08-18 11:33:22,897:INFO:Plot type: confusion_matrix
2023-08-18 11:33:22,981:INFO:Fitting Model
2023-08-18 11:33:22,981:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

2023-08-18 11:33:22,981:INFO:Scoring test/hold-out set
2023-08-18 11:33:23,047:INFO:Visual Rendered Successfully
2023-08-18 11:33:23,116:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:27,318:INFO:Initializing plot_model()
2023-08-18 11:33:27,318:INFO:plot_model(plot=threshold, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:27,318:INFO:Checking exceptions
2023-08-18 11:33:27,320:INFO:Preloading libraries
2023-08-18 11:33:27,320:INFO:Copying training dataset
2023-08-18 11:33:27,320:INFO:Plot type: threshold
2023-08-18 11:33:27,405:INFO:Fitting Model
2023-08-18 11:33:29,388:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

2023-08-18 11:33:29,399:INFO:Scoring test/hold-out set
2023-08-18 11:33:29,564:INFO:Visual Rendered Successfully
2023-08-18 11:33:29,636:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:35,999:INFO:Initializing plot_model()
2023-08-18 11:33:35,999:INFO:plot_model(plot=pr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:35,999:INFO:Checking exceptions
2023-08-18 11:33:36,000:INFO:Preloading libraries
2023-08-18 11:33:36,001:INFO:Copying training dataset
2023-08-18 11:33:36,001:INFO:Plot type: pr
2023-08-18 11:33:36,085:INFO:Fitting Model
2023-08-18 11:33:36,086:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

2023-08-18 11:33:36,086:INFO:Scoring test/hold-out set
2023-08-18 11:33:36,178:INFO:Visual Rendered Successfully
2023-08-18 11:33:36,258:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:37,919:INFO:Initializing plot_model()
2023-08-18 11:33:37,919:INFO:plot_model(plot=error, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:37,919:INFO:Checking exceptions
2023-08-18 11:33:37,920:INFO:Preloading libraries
2023-08-18 11:33:37,920:INFO:Copying training dataset
2023-08-18 11:33:37,920:INFO:Plot type: error
2023-08-18 11:33:38,005:INFO:Fitting Model
2023-08-18 11:33:38,005:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

2023-08-18 11:33:38,005:INFO:Scoring test/hold-out set
2023-08-18 11:33:38,106:INFO:Visual Rendered Successfully
2023-08-18 11:33:38,198:INFO:plot_model() successfully completed......................................
2023-08-18 11:33:39,126:INFO:Initializing plot_model()
2023-08-18 11:33:39,126:INFO:plot_model(plot=class_report, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), use_train_data=False, verbose=False, display=None, display_format=None, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, system=True)
2023-08-18 11:33:39,126:INFO:Checking exceptions
2023-08-18 11:33:39,128:INFO:Preloading libraries
2023-08-18 11:33:39,128:INFO:Copying training dataset
2023-08-18 11:33:39,128:INFO:Plot type: class_report
2023-08-18 11:33:39,213:INFO:Fitting Model
2023-08-18 11:33:39,213:WARNING:c:\Users\Admin\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

2023-08-18 11:33:39,213:INFO:Scoring test/hold-out set
2023-08-18 11:33:39,328:INFO:Visual Rendered Successfully
2023-08-18 11:33:39,398:INFO:plot_model() successfully completed......................................
2023-08-18 11:36:45,638:INFO:Initializing predict_model()
2023-08-18 11:36:45,639:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001F15801D310>)
2023-08-18 11:36:45,639:INFO:Checking exceptions
2023-08-18 11:36:45,639:INFO:Preloading libraries
2023-08-18 11:37:39,256:INFO:Initializing predict_model()
2023-08-18 11:37:39,256:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001F157E80310>)
2023-08-18 11:37:39,256:INFO:Checking exceptions
2023-08-18 11:37:39,256:INFO:Preloading libraries
2023-08-18 11:38:14,372:INFO:Initializing predict_model()
2023-08-18 11:38:14,373:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001F120FCE8E0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001F158061CA0>)
2023-08-18 11:38:14,373:INFO:Checking exceptions
2023-08-18 11:38:14,373:INFO:Preloading libraries
